name: Build and Package

on:
  workflow_dispatch: # 使工作流可以手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # 或您项目所需的其他版本

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Package as zip
        run: |
          zip -r package.zip . -x ".git/*" # 将项目内容压缩成名为 package.zip 的文件，排除.git目录

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: package.zip
